cordon_dry_run: {{cnf['repair-manager']['ecc_rule']['cordon_dry_run']}}
reboot_dry_run: {{cnf['repair-manager']['ecc_rule']['reboot_dry_run']}}

prometheus:
  ip: {{cnf['repair-manager']['prometheus-ip']}}
  port: {{cnf['repair-manager']['prometheus-port']}}
  ecc_error_query: 'nvidiasmi_ecc_error_count{type="volatile_double"}>0'
  node_boot_time_query: 'node_boot_time_seconds'

rest_url: {{cnf['repair-manager']['rest_url']}}
time_sleep_after_pausing: {{cnf['repair-manager']['time_sleep_after_pausing']}}

alert_job_owners: {{cnf['repair-manager']['ecc_rule']['alert_job_owners']}}

dri_email: {{cnf['repair-manager']['ecc_rule']['dri_email']}}

days_until_node_reboot: {{cnf['repair-manager']['ecc_rule']['days_until_node_reboot']}}
