smtp_url: {{cnf['repair-manager']['alert']['smtp_url']}}
login: {{cnf['repair-manager']['alert']['login']}}
password: {{cnf['repair-manager']['alert']['password']}}
sender: {{cnf['repair-manager']['alert']['sender']}}
receiver: {{cnf['repair-manager']['alert']['receiver']}}

# time to wait before resending email alert for exceptions (hours)
alert_wait_seconds: {{cnf['repair-manager']['alert']['alert_wait_seconds']}}