{
 "title": "DLTS Job Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job_name",
    "label": "job_id",
    "query": "label_values(task_cpu_percent, job_name)"
   }
  ]
 },
 "panels": [
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Assigned GPUs",
   "type": "singlestat",
   "description": "Number of GPUs assigned to the job.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_gpu_percent{job_name=\"$job_name\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Active GPUs",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_gpu_percent{job_name=\"$job_name\"}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle GPUs",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(task_gpu_percent{job_name=\"$job_name\"}) OR on() vector(0)) - (count(task_gpu_percent{job_name=\"$job_name\"}>0) OR on() vector(0))"
    }
   ]
  },
  { "title": "GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Assigned GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the job.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{job_name=\"$job_name\"})"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the job in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{job_name=\"$job_name\"})"
    }
   ]
  },
  {
   "title": "Active GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{job_name=\"$job_name\"}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Active Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the job over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{job_name=\"$job_name\"}>0)"
    }
   ]
  },
  { "title": "Resource Per Active GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "GPU Memory",
   "type": "singlestat",
   "description": "Average GPU memory utilization across all active GPUs (>0%) in the job.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((task_gpu_percent{job_name=\"$job_name\"} > bool 0) * task_gpu_mem_percent{job_name=\"$job_name\"}) / count(task_gpu_percent{job_name=\"$job_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "CPU usage per active GPU in the job.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_cpu_percent{job_name=\"$job_name\"}) / count(task_gpu_percent{job_name=\"$job_name\"}>0) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Memory usage per active GPU in the job.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 15 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte{job_name=\"$job_name\"}) / count(task_gpu_percent{job_name=\"$job_name\"}>0))OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "singlestat",
   "description": "Block In Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte{job_name=\"$job_name\"}[5m])) / count(task_gpu_percent{job_name=\"$job_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "singlestat",
   "description": "Block Out Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_out_byte{job_name=\"$job_name\"}[5m])) / count(task_gpu_percent{job_name=\"$job_name\"}>0))OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "singlestat",
   "description": "Network In Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte{job_name=\"$job_name\"}[5m])) / count(task_gpu_percent{job_name=\"$job_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "singlestat",
   "description": "Network Out Rate per active GPU in the job.",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_out_byte{job_name=\"$job_name\"}[5m])) / count(task_gpu_percent{job_name=\"$job_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  { "title": "Time Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "description": "GPU utilization for all GPUs in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_gpu_percent{job_name=\"$job_name\"}) by (minor_number, instance)",
     "legendFormat": "GPU {{minor_number}} on {{instance}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "description": "GPU memory utilization for all GPUs in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_gpu_mem_percent{job_name=\"$job_name\"}) by (minor_number, instance)",
     "legendFormat": "GPU {{minor_number}} on {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "CPU usage in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "avg(task_cpu_percent{job_name=\"$job_name\"}) by (instance) / 100",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory usage in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(task_mem_usage_byte{job_name=\"$job_name\"}) by (instance)",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "description": "Disk IO rate in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_block_in_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{instance}} In"
    },
    {
     "expr": "sum(rate(task_block_out_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{instance}} Out"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "description": "Network I/O rate in the job.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_net_in_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{instance}} In"
    },
    {
     "expr": "sum(rate(task_net_out_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": " {{instance}} Out"
    }
   ]
  }
 ]
}