{
 "title": "DLTS Cluster Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total GPUs",
   "type": "singlestat",
   "description": "Number of GPUs in the cluster.\n\nTODO: Currently it's showing k8s capacity. Ideally it should all underlying GPUs.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(k8s_node_gpu_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Assignable GPUs",
   "type": "singlestat",
   "description": "Number of GPUs immediately assignable to jobs.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(k8s_node_gpu_available)" }
   ]
  },
  {
   "title": "Unhealthy GPUs",
   "type": "singlestat",
   "description": "Number of unhealthy GPUs in k8s or marked as unschedulable.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(k8s_node_gpu_total) - sum(k8s_node_gpu_allocatable)"
    }
   ]
  },
  {
   "title": "Assigned GPUs",
   "type": "singlestat",
   "description": "Number of GPUs assigned to jobs.\n\nTODO: Exclude unhealthy but in use GPUs.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_gpu_percent) OR on() vector(0)",
     "legendFormat": "Assigned"
    }
   ]
  },
  {
   "title": "Active GPUs",
   "type": "singlestat",
   "description": "Number of assigned GPUs having utilization > 0%.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_gpu_percent>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle GPUs",
   "type": "singlestat",
   "description": "Number of assigned GPUs having utilization 0%.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(task_gpu_percent) OR on() vector(0)) - (count(task_gpu_percent>0) OR on() vector(0))"
    }
   ]
  },
  { "title": "GPU Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "GPUs",
   "type": "graph",
   "description": "GPU numbers in the cluster over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(k8s_node_gpu_total)", "legendFormat": "Total" },
    { "expr": "sum(k8s_node_gpu_available)", "legendFormat": "Assignable" },
    {
     "expr": "sum(k8s_node_gpu_total) - sum(k8s_node_gpu_allocatable)",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "count(task_gpu_percent) OR on() vector(0)",
     "legendFormat": "Assigned"
    },
    {
     "expr": "count(task_gpu_percent>0) OR on() vector(0)",
     "legendFormat": "Active"
    },
    {
     "expr": "(count(task_gpu_percent) OR on() vector(0)) - (count(task_gpu_percent>0) OR on() vector(0))",
     "legendFormat": "Idle"
    }
   ]
  },
  { "title": "GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Cluster GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all GPUs in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_gpu_percent) / sum(k8s_node_gpu_total)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Cluster GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utlization across all GPUs in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(task_gpu_percent) / sum(k8s_node_gpu_total)"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_gpu_percent) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(task_gpu_percent)", "legendFormat": "Assigned GPU Util" }
   ]
  },
  {
   "title": "Active GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the cluster.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_gpu_percent>0) OR on() vector(0)",
     "legendFormat": "Assigned GPU Util"
    }
   ]
  },
  {
   "title": "Active GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the cluster over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    { "expr": "avg(task_gpu_percent>0)", "legendFormat": "Assigned GPU Util" }
   ]
  },
  { "title": "GPU Utilization Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "description": "Average GPU utilization in the cluster over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(task_gpu_percent) / sum(k8s_node_gpu_total)",
     "legendFormat": "Cluster"
    },
    { "expr": "avg(task_gpu_percent)", "legendFormat": "Assigned" },
    { "expr": "avg(task_gpu_percent>0)", "legendFormat": "Active" }
   ]
  },
  { "title": "GPU Fragmentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Node Count By Assignable GPUs",
   "type": "graph",
   "description": "Histogram showing number of nodes with assignable GPUs in the cluster.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Node count" }
   ],
   "targets": [
    { "expr": "k8s_node_gpu_available" }
   ]
  },
  {
   "title": "Node Count By Assignable GPUs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Node count" }
   ],
   "targets": [
    {
     "expr": "count_values(\"gpu_available\", k8s_node_gpu_available)",
     "legendFormat": "{{gpu_available}}"
    }
   ]
  },
  { "title": "Job Status Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "unapproved -> queued",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 43 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"approved\"} / job_state_change_latency_seconds_count{current_state=\"approved\"})"
    }
   ]
  },
  {
   "title": "queued -> scheduling",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 43 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"scheduling\"} / job_state_change_latency_seconds_count{current_state=\"scheduling\"})"
    }
   ]
  },
  {
   "title": "scheduling -> running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 43 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"running\"} / job_state_change_latency_seconds_count{current_state=\"running\"})"
    }
   ]
  },
  { "title": "Job Status Latency Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Average Job Status Change Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"approved\"} / job_state_change_latency_seconds_count{current_state=\"approved\"})",
     "legendFormat": "unapproved -> queued"
    },
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"scheduling\"} / job_state_change_latency_seconds_count{current_state=\"scheduling\"})",
     "legendFormat": "queued -> scheduling"
    },
    {
     "expr": "avg(job_state_change_latency_seconds_sum{current_state=\"running\"} / job_state_change_latency_seconds_count{current_state=\"running\"})",
     "legendFormat": "scheduling -> running"
    }
   ]
  },
  { "title": "Resource Per Active GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "GPU Memory",
   "type": "singlestat",
   "description": "Average GPU memory utilization per GPU across all active GPUs (>0%) in the cluster.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 56 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((task_gpu_percent > bool 0) * task_gpu_mem_percent) / count(task_gpu_percent>0)) OR on() vector(0)",
     "legendFormat": "Assigned GPU Util"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "Average CPU usage per GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_cpu_percent.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 56 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_cpu_percent) / count(task_gpu_percent>0) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Average memory usage per GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_mem_usage_byte.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 56 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte) / count(task_gpu_percent>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "singlestat",
   "description": "Average disk read rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_block_in_byte.",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 56 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte[5m])) / count(task_gpu_percent>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "singlestat",
   "description": "Average disk write rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_block_out_byte.",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 56 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_out_byte[5m])) / count(task_gpu_percent>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "singlestat",
   "description": "Average network inbound rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_net_in_byte.",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 56 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte[5m])) / count(task_gpu_percent>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "singlestat",
   "description": "Average network outbound rate per active GPU across all active GPUs (>0%) in the cluster.\n\nTODO: Distinguish 0 GPU task_net_out_byte.",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 56 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_out_byte[5m])) / count(task_gpu_percent>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Resource Per Active GPU Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "GPU Memory Per Active GPU",
   "type": "graph",
   "description": "Average GPU memory utilization per active GPU in the cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum((task_gpu_percent > bool 0) * task_gpu_mem_percent) / count(task_gpu_percent>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU Per Active GPU",
   "type": "graph",
   "description": "Average CPU usage per active GPU in the cluster over time.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "(sum(task_cpu_percent) / count(task_gpu_percent>0) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Memory Per Active GPU",
   "type": "graph",
   "description": "Average memory usage per active GPU in the cluster.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte) / count(task_gpu_percent>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk I/O Per Active GPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte[5m])) / count(task_gpu_percent>0)) OR on() vector(0)",
     "legendFormat": "In"
    },
    {
     "expr": "(sum(rate(task_block_out_byte[5m])) / count(task_gpu_percent>0) OR on() vector(0))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network I/O Per Active GPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte[5m])) / count(task_gpu_percent>0)) OR on() vector(0)",
     "legendFormat": "In"
    },
    {
     "expr": "(sum(rate(task_net_out_byte[5m])) / count(task_gpu_percent>0) OR on() vector(0))",
     "legendFormat": "Out"
    }
   ]
  },
  { "title": "VC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "VC Allocated GPUs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_vc_gpu_total) by (vc_name)",
     "legendFormat": "{{vc_name}}"
    }
   ]
  },
  {
   "title": "VC Allocation Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(k8s_vc_gpu_total) by (vc_name) / ignoring (vc_name) group_left sum(k8s_vc_gpu_total)",
     "legendFormat": "{{vc_name}}"
    }
   ]
  },
  {
   "title": "VC Allocated GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(task_gpu_percent) by (vc_name) / sum(k8s_vc_gpu_total) by (vc_name)",
     "legendFormat": "{{vc_name}}"
    }
   ]
  },
  {
   "title": "VC Assigned GPUs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(task_gpu_percent) by (vc_name)",
     "legendFormat": "{{vc_name}}"
    }
   ]
  },
  {
   "title": "VC Assignment GPU Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count(task_gpu_percent) by (vc_name) / sum(k8s_vc_gpu_total) by (vc_name)",
     "legendFormat": "{{vc_name}}"
    }
   ]
  },
  {
   "title": "VC Assigned GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_gpu_percent) by (vc_name)",
     "legendFormat": "{{vc_name}}"
    }
   ]
  },
  {
   "title": "VC Active GPUs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(task_gpu_percent>0) by (vc_name)",
     "legendFormat": "{{vc_name}}"
    }
   ]
  },
  {
   "title": "VC Active GPU Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 90 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count(task_gpu_percent>0) by (vc_name) / count(task_gpu_percent) by (vc_name)",
     "legendFormat": "{{vc_name}}"
    }
   ]
  },
  {
   "title": "VC Active GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 90 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_gpu_percent>0) by (vc_name)",
     "legendFormat": "{{vc_name}}"
    }
   ]
  }
 ]
}