{
 "title": "DLTS User Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "username",
    "query": "label_values(task_cpu_percent, username)"
   },
   {
    "name": "vc_name",
    "query": "label_values(task_cpu_percent{username=\"$username\"}, vc_name)"
   }
  ]
 },
 "panels": [
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Assigned GPUs",
   "type": "singlestat",
   "description": "Number of GPUs assigned to the user.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_gpu_percent{username=\"$username\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Active GPUs",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_gpu_percent{username=\"$username\"}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle GPUs",
   "type": "singlestat",
   "description": "Number of idle GPUs under  the user.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(task_gpu_percent{username=\"$username\"}) OR on() vector(0)) - (count(task_gpu_percent{username=\"$username\"}>0) OR on() vector(0))"
    }
   ]
  },
  { "title": "GPU Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "GPUs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}) OR on() vector(0)",
     "legendFormat": "Assigned"
    },
    {
     "expr": "count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0) OR on() vector(0)",
     "legendFormat": "Active"
    },
    {
     "expr": "(count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}) OR on() vector(0)) - (count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0) OR on() vector(0))",
     "legendFormat": "Idle"
    }
   ]
  },
  { "title": "GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Assigned GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs to the user.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{username=\"$username\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs to the user over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{username=\"$username\"})"
    }
   ]
  },
  {
   "title": "Active GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{username=\"$username\"}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Active GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) assigned to the user over the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{username=\"$username\"}>0)"
    }
   ]
  },
  { "title": "GPU Utilization Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}) OR on() vector(0)",
     "legendFormat": "Assigned"
    },
    {
     "expr": "avg(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0) OR on() vector(0)",
     "legendFormat": "Active"
    },
    {
     "expr": "avg(task_gpu_percent{vc_name=\"$vc_name\"}) OR on() vector(0)",
     "legendFormat": "VC Assigned"
    },
    {
     "expr": "avg(task_gpu_percent{vc_name=\"$vc_name\"}>0) OR on() vector(0)",
     "legendFormat": "VC Active"
    }
   ]
  },
  { "title": "Resource Per Active GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "GPU Memory",
   "type": "singlestat",
   "description": "Average GPU memory utilization across all active GPUs (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"} > bool 0) * task_gpu_mem_percent{username=\"$username\",vc_name=\"$vc_name\"}) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "CPU usage per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 31 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_cpu_percent{username=\"$username\",vc_name=\"$vc_name\"}) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Memory usage per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 31 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte{username=\"$username\",vc_name=\"$vc_name\"}) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "singlestat",
   "description": "Block In Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 31 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "singlestat",
   "description": "Block Out Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 31 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "singlestat",
   "description": "Network Inbound Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 31 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "singlestat",
   "description": "Network Outbound Rate per active GPU (>0%) assigned to the user.",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 31 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Resource Per Active GPU Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "GPU Memory Per Active GPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum((task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"} > bool 0) * task_gpu_mem_percent{username=\"$username\",vc_name=\"$vc_name\"}) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "User"
    },
    {
     "expr": "(sum((task_gpu_percent{vc_name=\"$vc_name\"} > bool 0) * task_gpu_mem_percent{vc_name=\"$vc_name\"}) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC"
    }
   ]
  },
  {
   "title": "CPU Per Active GPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(task_cpu_percent{username=\"$username\",vc_name=\"$vc_name\"}) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0) / 100) OR on() vector(0)",
     "legendFormat": "User"
    },
    {
     "expr": "(sum(task_cpu_percent{vc_name=\"$vc_name\"}) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0) / 100) OR on() vector(0)",
     "legendFormat": "VC"
    }
   ]
  },
  {
   "title": "Memory Per Active GPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte{username=\"$username\",vc_name=\"$vc_name\"}) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "User"
    },
    {
     "expr": "(sum(task_mem_usage_byte{vc_name=\"$vc_name\"}) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC"
    }
   ]
  },
  {
   "title": "Disk I/O Per Active GPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "User In"
    },
    {
     "expr": "(sum(rate(task_block_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "User Out"
    },
    {
     "expr": "(sum(rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC In"
    },
    {
     "expr": "(sum(rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC Out"
    }
   ]
  },
  {
   "title": "Network I/O Per Active GPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "User In"
    },
    {
     "expr": "(sum(rate(task_net_out_byte{username=\"$username\",vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{username=\"$username\",vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "User Out"
    },
    {
     "expr": "(sum(rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC In"
    },
    {
     "expr": "(sum(rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC Out"
    }
   ]
  }
 ]
}