{
 "title": "DLTS VC Statistics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "vc_name",
    "label": "vc_name",
    "query": "label_values(k8s_vc_gpu_total, vc_name)"
   }
  ]
 },
 "panels": [
  { "title": "GPUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Allocated",
   "type": "singlestat",
   "description": "Number of GPUs allocated to the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_gpu_total{vc_name=\"$vc_name\"})",
     "legendFormat": "Allocated GPUs"
    }
   ]
  },
  {
   "title": "Assignable GPUs",
   "type": "singlestat",
   "description": "Number of GPUs immediately assignable to jobs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_gpu_available{vc_name=\"$vc_name\"})"
    }
   ]
  },
  {
   "title": "Unhealthy GPUs",
   "type": "singlestat",
   "description": "Number of unhealthy GPUs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(k8s_vc_gpu_unschedulable{vc_name=\"$vc_name\"})",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Assigned GPUs",
   "type": "singlestat",
   "description": "Number of GPUs assigned to jobs in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_gpu_percent{vc_name=\"$vc_name\"}) OR on() vector(0)",
     "legendFormat": "Assigned"
    }
   ]
  },
  {
   "title": "Active GPUs",
   "type": "singlestat",
   "description": "Number of active GPUs (>0%) in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(task_gpu_percent{vc_name=\"$vc_name\"}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Idle GPUs",
   "type": "singlestat",
   "description": "Number of assigned GPUs having utilization 0% in the VC.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(task_gpu_percent{vc_name=\"$vc_name\"}) OR on() vector(0)) - (count(task_gpu_percent{vc_name=\"$vc_name\"}>0) OR on() vector(0))"
    }
   ]
  },
  { "title": "GPU Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "GPUs",
   "type": "graph",
   "description": "GPU numbers in the VC over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(k8s_vc_gpu_total{vc_name=\"$vc_name\"})",
     "legendFormat": "Allocated"
    },
    {
     "expr": "avg(k8s_vc_gpu_available{vc_name=\"$vc_name\"})",
     "legendFormat": "Assignable"
    },
    {
     "expr": "avg(k8s_vc_gpu_unschedulable{vc_name=\"$vc_name\"})",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "count(task_gpu_percent{vc_name=\"$vc_name\"}) OR on() vector(0)",
     "legendFormat": "Assigned"
    },
    {
     "expr": "count(task_gpu_percent{vc_name=\"$vc_name\"}>0) OR on() vector(0)",
     "legendFormat": "Active"
    },
    {
     "expr": "(count(task_gpu_percent{vc_name=\"$vc_name\"}) OR on() vector(0)) - (count(task_gpu_percent{vc_name=\"$vc_name\"}>0) OR on() vector(0))",
     "legendFormat": "Idle"
    }
   ]
  },
  { "title": "GPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Allocated GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all GPUs allocated to the VC.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(task_gpu_percent{vc_name=\"$vc_name\"}) / sum(k8s_vc_gpu_total{vc_name=\"$vc_name\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Allocated GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all GPUs in the VC in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(task_gpu_percent{vc_name=\"$vc_name\"}) / sum(k8s_vc_gpu_total{vc_name=\"$vc_name\"})"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the VC.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{vc_name=\"$vc_name\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all assigned GPUs in the VC in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{vc_name=\"$vc_name\"})"
    }
   ]
  },
  {
   "title": "Active GPU Utilization",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the VC.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{vc_name=\"$vc_name\"}>0) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Active GPU Utilization Over Time",
   "type": "singlestat",
   "description": "Average GPU utilization across all active GPUs (>0%) in the VC in the selected time range.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(task_gpu_percent{vc_name=\"$vc_name\"}>0)"
    }
   ]
  },
  { "title": "GPU Utilization Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "description": "Average GPU utilization in the VC over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(task_gpu_percent{vc_name=\"$vc_name\"}) / sum(k8s_vc_gpu_total)",
     "legendFormat": "Allocated"
    },
    {
     "expr": "avg(task_gpu_percent{vc_name=\"$vc_name\"})",
     "legendFormat": "Assigned"
    },
    {
     "expr": "avg(task_gpu_percent{vc_name=\"$vc_name\"}>0)",
     "legendFormat": "Active"
    }
   ]
  },
  { "title": "Resource Per Active GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "GPU Memory",
   "type": "singlestat",
   "description": "Average GPU memory utilization across all active GPUs (>0%) in the VC.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 35 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum((task_gpu_percent{vc_name=\"$vc_name\"} > bool 0) * task_gpu_mem_percent{vc_name=\"$vc_name\"}) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "description": "Average CPU usage per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_cpu_percent.",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 35 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_cpu_percent{vc_name=\"$vc_name\"}) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0) / 100) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "description": "Average memory usage per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_mem_usage_byte.",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 35 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte{vc_name=\"$vc_name\"}) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Read",
   "type": "singlestat",
   "description": "Average disk read rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_block_in_byte.",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 35 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Disk Write",
   "type": "singlestat",
   "description": "Average disk write rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_block_out_byte.",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 35 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "singlestat",
   "description": "Average network inbound rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_net_in_byte.",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 35 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "singlestat",
   "description": "Average network outbound rate per GPU across all active GPUs (>0%) in the VC.\n\nTODO: Distinguish 0 GPU task_net_out_byte.",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 35 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 35 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  {
   "title": "Resource Per Active GPU Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "GPU Memory Per Active GPU",
   "type": "graph",
   "description": "Average GPU memory utilization per active GPU.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum((task_gpu_percent{vc_name=\"$vc_name\"} > bool 0) * task_gpu_mem_percent{vc_name=\"$vc_name\"}) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC"
    },
    {
     "expr": "(sum((task_gpu_percent > bool 0) * task_gpu_mem_percent) / count(task_gpu_percent>0)) OR on() vector(0)",
     "legendFormat": "Cluster"
    }
   ]
  },
  {
   "title": "CPU Per Active GPU",
   "type": "graph",
   "description": "Average CPU usage per active GPU.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Core" }
   ],
   "targets": [
    {
     "expr": "(sum(task_cpu_percent{vc_name=\"$vc_name\"}) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0) / 100) OR on() vector(0)",
     "legendFormat": "VC"
    },
    {
     "expr": "(sum(task_cpu_percent) / count(task_gpu_percent>0) / 100) OR on() vector(0)",
     "legendFormat": "Cluster"
    }
   ]
  },
  {
   "title": "Memory Usage Per GPU",
   "type": "graph",
   "description": "Average memory usage per active GPU.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(task_mem_usage_byte{vc_name=\"$vc_name\"}) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC"
    },
    {
     "expr": "(sum(task_mem_usage_byte) / count(task_gpu_percent>0)) OR on() vector(0)",
     "legendFormat": "Cluster"
    }
   ]
  },
  {
   "title": "Disk I/O Per Active GPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_block_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC In"
    },
    {
     "expr": "(sum(rate(task_block_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC Out"
    },
    {
     "expr": "(sum(rate(task_block_in_byte[5m])) / count(task_gpu_percent>0)) OR on() vector(0)",
     "legendFormat": "Cluster In"
    },
    {
     "expr": "(sum(rate(task_block_out_byte[5m])) / count(task_gpu_percent>0)) OR on() vector(0)",
     "legendFormat": "Cluster Out"
    }
   ]
  },
  {
   "title": "Network I/O Per Active GPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(task_net_in_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC In"
    },
    {
     "expr": "(sum(rate(task_net_out_byte{vc_name=\"$vc_name\"}[5m])) / count(task_gpu_percent{vc_name=\"$vc_name\"}>0)) OR on() vector(0)",
     "legendFormat": "VC Out"
    },
    {
     "expr": "(sum(rate(task_net_in_byte[5m])) / count(task_gpu_percent>0)) OR on() vector(0)",
     "legendFormat": "Cluster In"
    },
    {
     "expr": "(sum(rate(task_net_out_byte[5m])) / count(task_gpu_percent>0)) OR on() vector(0)",
     "legendFormat": "Cluster Out"
    }
   ]
  },
  { "title": "User", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Assigned GPU By User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(task_gpu_percent{vc_name=\"$vc_name\"}) by (username)",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Assigned GPU Utilization By User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_gpu_percent{vc_name=\"$vc_name\"}) by (username)",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Active GPU By User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(task_gpu_percent{vc_name=\"$vc_name\"}>0) by (username)",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Active GPU Utilization By User",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(task_gpu_percent{vc_name=\"$vc_name\"}>0) by (username)",
     "legendFormat": "{{username}}"
    }
   ]
  }
 ]
}