{
 "title": "Job Status",
 "description": "Dashboard to view job metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job_name",
    "query": "label_values(task_cpu_percent, job_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "task_gpu_percent{job_name=\"$job_name\"}",
     "legendFormat": "GPU {{minor_number}} on {{instance}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "task_gpu_mem_percent{job_name=\"$job_name\"}",
     "legendFormat": "GPU {{minor_number}} on {{instance}}"
    }
   ]
  },
  {
   "title": "GPU DCGM Util",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "task_dcgm_gpu_util{job_name=\"$job_name\"}",
     "legendFormat": "GPU {{minor_number}} on {{instance}}"
    }
   ]
  },
  {
   "title": "GPU DCGM Mem Copy Util",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "task_dcgm_mem_copy_util{job_name=\"$job_name\"}",
     "legendFormat": "GPU {{minor_number}} on {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "task_cpu_percent{job_name=\"$job_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "task_mem_usage_byte{job_name=\"$job_name\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_net_in_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Inbound"
    },
    {
     "expr": "sum(rate(task_net_out_byte{job_name=\"$job_name\"}[5m])) by (instance)",
     "legendFormat": "{{instance}} Outbound"
    }
   ]
  },
  {
   "title": "Block IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(task_block_in_byte{job_name=\"$job_name\"}[300s])",
     "legendFormat": "{{instance}} Read"
    },
    {
     "expr": "irate(task_block_out_byte{job_name=\"$job_name\"}[300s])",
     "legendFormat": "{{instance}} Write"
    }
   ]
  },
  {
   "title": "Infiniband",
   "type": "graph",
   "description": "I/O via Infiniband devices. Available only for distributed jobs in Infiniband enabled clusters using Mellanox OFED driver.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_infiniband_receive_bytes_total{job_name=\"$job_name\", link_layer=\"InfiniBand\", role_name=\"worker\"}[5m])) by (instance, device, port)",
     "legendFormat": "{{instance}} {{device}}:{{port}} Inbound"
    },
    {
     "expr": "sum(rate(task_infiniband_transmit_bytes_total{job_name=\"$job_name\", link_layer=\"InfiniBand\", role_name=\"worker\"}[5m])) by (instance, device, port)",
     "legendFormat": "{{instance}} {{device}}:{{port}} Outbound"
    }
   ]
  },
  {
   "title": "IPoIB",
   "type": "graph",
   "description": "I/O via IPoIB interfaces. Available only for distributed jobs in Infiniband enabled clusters.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(task_ipoib_receive_bytes_total{job_name=\"$job_name\", role_name=\"worker\"}[5m])) by (instance, device)",
     "legendFormat": "{{instance}} {{device}} Inbound"
    },
    {
     "expr": "sum(rate(task_ipoib_transmit_bytes_total{job_name=\"$job_name\", role_name=\"worker\"}[5m])) by (instance, device)",
     "legendFormat": "{{instance}} {{device}} Outbound"
    }
   ]
  }
 ]
}