{
 "title": "Lustre",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Healthy MDS",
   "type": "singlestat",
   "description": "# of healthy MDS",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(lustre_health_check{server=\"mds\"})"
    }
   ]
  },
  {
   "title": "Healthy OSS",
   "type": "singlestat",
   "description": "# of healthy OSS",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(lustre_health_check{server=\"oss\"})"
    }
   ]
  },
  {
   "title": "Healthy Clients",
   "type": "singlestat",
   "description": "# of healthy clients",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(lustre_health_check{server=\"client\"})"
    }
   ]
  },
  {
   "title": "OST Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(lustre_capacity_kilobytes{role=\"ost\"})"
    }
   ]
  },
  {
   "title": "OST Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(lustre_capacity_kilobytes{role=\"ost\"}) - sum(lustre_available_kilobytes{role=\"ost\"})"
    }
   ]
  },
  {
   "title": "OST Storage Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(lustre_capacity_kilobytes{role=\"ost\"}) by (target) - sum(lustre_available_kilobytes{role=\"ost\"}) by (target)) / (sum(lustre_capacity_kilobytes{role=\"ost\"}) by (target))",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "(sum(lustre_capacity_kilobytes{role=\"ost\"}) - sum(lustre_available_kilobytes{role=\"ost\"})) / sum(lustre_capacity_kilobytes{role=\"ost\"})",
     "legendFormat": "Aggregate"
    }
   ]
  },
  {
   "title": "OST Inode Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(lustre_inodes_maximum{role=\"ost\"}) by (target) - sum(lustre_inodes_free{role=\"ost\"}) by (target)) / (sum(lustre_inodes_maximum{role=\"ost\"}) by (target))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "IO bandwidth",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_write_bytes_total[2m])) by (target)",
     "legendFormat": "{{target}} write"
    },
    {
     "expr": "sum(rate(lustre_read_bytes_total[2m])) by (target)",
     "legendFormat": "{{target}} read"
    },
    {
     "expr": "sum(rate(lustre_write_bytes_total[2m]))",
     "legendFormat": "Aggregate write"
    },
    {
     "expr": "sum(rate(lustre_read_bytes_total[2m]))",
     "legendFormat": "Aggregate read"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_write_samples_total[2m])) by (target)",
     "legendFormat": "{{target}} write"
    },
    {
     "expr": "sum(rate(lustre_read_samples_total[2m])) by (target)",
     "legendFormat": "{{target}} read"
    },
    {
     "expr": "sum(rate(lustre_write_samples_total[2m]))",
     "legendFormat": "Aggregate write"
    },
    {
     "expr": "sum(rate(lustre_read_samples_total[2m]))",
     "legendFormat": "Aggregate read"
    }
   ]
  },
  {
   "title": "Metadata Ops",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(lustre_stats_total[2m])) by (target, operation)",
     "legendFormat": "{{target}} {{operation}}"
    },
    {
     "expr": "sum(rate(lustre_stats_total[2m]))",
     "legendFormat": "Aggregate"
    }
   ]
  },
  {
   "title": "Num Exports",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(lustre_num_exports) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}