{
 "title": "Node Repair State",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "sku",
    "query": "label_values(repair_state_node_count, sku)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Count By Repair State (Current)",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(repair_state_node_count{sku=~\"$sku\"}) by (repair_state, sku)"
    }
   ]
  },
  {
   "title": "Node Count By Repair State",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(repair_state_node_count{sku=~\"$sku\"}) by (repair_state, sku)",
     "legendFormat": "{{repair_state}} {{sku}}"
    }
   ]
  },
  {
   "title": "Node Count By Repair Rule (Current)",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(repair_rule_node_count{sku=~\"$sku\"}) by (repair_rule, sku)"
    }
   ]
  },
  {
   "title": "Node Count By Repair Rule",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(repair_rule_node_count{sku=~\"$sku\"}) by (repair_rule, sku)",
     "legendFormat": "{{repair_rule}} {{sku}}"
    }
   ]
  },
  {
   "title": "Jobs Impacted By Repair (Current)",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(repair_impacted_job_count{sku=~\"$sku\"}) by (sku)"
    }
   ]
  },
  {
   "title": "Jobs Impacted By Repair",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(repair_impacted_job_count{sku=~\"$sku\"}) by (sku)",
     "legendFormat": "{{sku}}"
    }
   ]
  }
 ]
}