# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- citest

pool:
  name: 'DLTS-Platform'

# container: ubuntu:18.04

variables: { SUBSCRIPTION_NAME: "'Bing DLTS'"}

steps:
- script: |
    cd src/ClusterBootstrap/
    az account set --subscription $(SUBSCRIPTION_NAME)
  displayName: 'Set Subscription'

- script: |
    cd src/ClusterBootstrap/scripts
    CONFIG_TYPE="${CONFIG_TYPE:-cpu}"
    echo $CONFIG_TYPE
    ./set_config.sh $CONFIG_TYPE
    cd ..
    ./deploy.sh
  displayName: 'Deploy DLWorkspace'

- script: |
    cd src/ClusterBootstrap/
    USER=$(grep -B3 admin_username az_complementary.yaml | awk '{print $2}')
    CONFIG_TYPE="${CONFIG_TYPE:-cpu}"
    WAITMIN="${WAITMIN:-5}"
    POLLSEC="${POLLSEC:-30}"
    echo $CONFIG_TYPE $WAITMIN $POLLSEC
    cd scripts
    ./verify_deployment.sh $USER $CONFIG_TYPE $WAITMIN $POLLSEC
  displayName: 'Verify deployment'

- script: |
    echo TODO: RUN functional tests!
  displayName: 'Functional tests'

- script: |
    cd src/ClusterBootstrap/
    RESOURCEGRP=$(grep cluster_name cluster.yaml|awk '{print $2}')ResGrp
    az group delete --name $RESOURCEGRP --yes
  displayName: 'Cleanup'
