#!/bin/bash


export GRAFANA_USER=grafana
export GRAFANA_GROUP=grafana
export GRAFANA_HOME=/usr/share/grafana
export LOG_DIR=/var/log/grafana
export DATA_DIR=/var/lib/grafana
export MAX_OPEN_FILES=10000
export CONF_DIR=/etc/grafana
export CONF_FILE=/etc/grafana/grafana.ini
export RESTART_ON_UPGRADE=true
export PLUGINS_DIR=/var/lib/grafana/plugins

fqdn=`cat /etc/hostname-fqdn`
command='s/hostname-fqdn/'$fqdn'/'
sed $command -i /etc/grafana/grafana.ini
echo sed $command -i /etc/grafana/grafana.ini
/usr/bin/init.sh &
/usr/sbin/grafana-server --config=/etc/grafana/grafana.ini -homepath=/usr/share/grafana cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/lib/grafana cfg:default.paths.plugins=/var/lib/grafana/plugins
