---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(filename)s:%(lineno)d - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: simple
    filename: /var/log/dlworkspace/repairmanager.log
    # roll over at 10MB
    maxBytes: 10240000
    # At most 10 logging files
    backupCount: 10
  stats:
    class : logging.handlers.RotatingFileHandler
    formatter: simple
    filename: /etc/RepairManager/activity.log
    maxBytes: 10240000
    backupCount: 2
loggers:
  basic:
    level: DEBUG
    handlers: ['console','file']
    propagate: no
  activity:
    level: INFO
    handlers: ['console','stats']
    propagate: no
root:
  level: DEBUG
  handlers: ['console','file']
