---  
# [Rule Module Name] : [Rule Class Name]
rules:
  Rules.ecc_rule : ECCRule
  
# time to sleep between rule execution
wait_time: 10

# prometheus ecc error query
ecc_prometheus_url: 'http://localhost:9091/prometheus/api/v1/query?query=nvidiasmi_ecc_error_count%7Btype%3D%22volatile_double%22%7D%3E0'

