---  
rules:
        ecc_rule:
                module_name : Rules.ecc_rule
                class_name : ECCRule
                ecc_error_url: '/api/v1/query?query=nvidiasmi_ecc_error_count%7Btype%3D%22volatile_double%22%7D%3E0'
  
# time to sleep between rule execution
rule_wait_time: 10

email_alerts:
    smtp_url: REPLACE SMTP URL
    login: REPLACE EMAIL LOGING
    password: REPLACE EMAIL PASSWORD
    sender: REPLACE EMAIL SENDER
    receiver: REPLACE EMAIL RECEIVER

# time to wait before resending email alert for exceptions (hours)
alert_wait_time: 2
