export const SUCCESSFULLYAPPROVED = 'Successfully scheduled for approving'
export const SUCCESSFULLYPAUSED = 'Successfully scheduled for  pausing'
export const SUCCESSFULLYRESUMED = 'Successfully scheduled for resuming'
export const SUCCESSFULLYUPDATEDPRIORITY = 'Successfully updated priority'
export const SUCESSFULKILLED = 'Successfully scheduled for killing'
export const SUCCESSFULSUBMITTED = 'Job submitted successfully'
export const SUCCESSFULTEMPLATEDELETE = 'Template deleted'
export const SUCCESSFULTEMPLATEDSAVE = 'Template saved'
